from sudoku_class import *
asudoku=sudoku()
asudoku.generate()
asudoku.display()
asudoku=sudoku()
asudoku.makepuzzle(40)
asudoku.display()
asudoku.solved()
asudoku.solve()
asudoku.display()
